# Generated by Django 5.2.17 on 2026-09-22 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import timezones.zones


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimezonePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic — use this device"),
                            ("fixed", "Always use the selected timezone"),
                        ],
                        default="automatic",
                        max_length=16,
                    ),
                ),
                (
                    "display_timezone",
                    models.CharField(
                        default="UTC", max_length=100, validators=[timezones.zones.validate_zone]
                    ),
                ),
                (
                    "reporting_timezone",
                    models.CharField(
                        default="UTC", max_length=100, validators=[timezones.zones.validate_zone]
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("occurred_at", models.DateTimeField()),
                (
                    "original_timezone",
                    models.CharField(max_length=100, validators=[timezones.zones.validate_zone]),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["user", "occurred_at"], name="timezones_e_user_id_7c85c2_idx"
                    )
                ],
            },
        ),
    ]
