# Generated by Django 5.2.17 on 2026-09-22 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timezones", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timezonepreference",
            name="mode",
        ),
    ]
