# Generated by Django 5.2.17 on 2026-09-22 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timezones", "0002_remove_timezonepreference_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimezonePrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("from_timezone", models.CharField(max_length=100)),
                ("to_timezone", models.CharField(max_length=100)),
                ("offered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "session_key", "from_timezone", "to_timezone"),
                        name="one_prompt_per_session_transition",
                    )
                ],
            },
        ),
    ]
