# Generated by Django 5.2.17 on 2026-09-23 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timezones", "0003_timezoneprompt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimezonePrompt",
        ),
    ]
